#!/bin/bash

function blog_backup() {
	
	before_dump=$(<blog_entries.sql)
	
	mysqldump -u root -p blog_entries > blog_entries.sql

	after_dump=$(<blog_entries.sql)

	if [ "$before_dump" != "$after_dump" ]; then
		echo "Backup Successful."
		exit 0
	else
		echo "Something went wrong. Your backup was not updated."
	fi

}
