#!/bin/bash

function blog_backup() {
	
	BEFORE_DUMP=$(<backup.sql)
	
	mysqldump -u root -p blog_entries > backup.sql

	AFTER_DUMP=$(<backup.sql)

	if [ "$BEFORE_DUMP" != "$AFTER_DUMP" ]; then
		echo "Backup Successful."
		exit 0
	else
		echo "Something went wrong. Your backup was not updated."
	fi

}
