#!/bin/bash

source "/usr/local/bin/blog_read"
source "/usr/local/bin/blog_write"
source "/usr/local/bin/blog_edit"
source "/usr/local/bin/blog_delete"
source "/usr/local/bin/blog_backup"
source "./publish"

MYSQL_HOST="localhost"
MYSQL_USER="root"
MYSQL_DATABASE="blog_entries"


if [ $# -eq 0 ]; then
	echo "An argument is mandatory, please run again with one of the following: 
	blog read
	blog write
	blog edit 
	blog delete 
	blog backup
	blog publish
	"
elif [ $1 == "read" ]; then
	blog_read "$2"
elif [ $1 == "write" ]; then
	blog_write "$2"
elif [ $1 == "edit" ]; then
	blog_edit "$2" "$3"
elif [ $1 == "delete" ]; then
	blog_delete "$2"
elif [ $1 == "backup" ]; then
	blog_backup "$2"
elif [ $1 == "publish" ]; then
	publish_tools "$2"
else
	echo -e "You've entered an invalid argument, please run again with one of the following:
        blog read
        blog write
        blog edit
        blog delete
        blog backup
	blog publish
  	"
fi
