#!/bin/bash

function execute_mysql() {
	
	DATABASE_NAME="blog_entries"
	CONTAINER_NAME="mysql_blog_interface"
	MYSQL_CONFIG_PATH="/usr/local/share/blog_config_mysql.cnf"
	BLOG_CONFIG_PATH="/usr/local/share/blog_config.yml"
	in_container="$(read_mysql_cnf Container)"
	sql="$1"

	# Determines whether the client is being run inside or outside the container, then:
	# Enters the DBMS, submits the query, and places the data in "output".
	case "$in_container" in
		True)
			output_dirty=$(mysql --defaults-extra-file="$MYSQL_CONFIG_PATH" -D "$DATABASE_NAME" -e "$sql")
			mysql_err="$?"
			;;
		False)
			output_dirty=$(docker-compose exec "$CONTAINER_NAME" mysql --defaults-extra-file="$MYSQL_CONFIG_PATH" -D "$DATABASE_NAME" -e "$sql")
			mysql_err=$(docker-compose exec "$CONTAINER_NAME" echo "$?")
			;;
		?)
			echo "You must have a \"Container: [True] | [False]\" configuration in "$BLOG_CONFIG_PATH""
			exit 1
			;;
	esac

	# Returns cleaned output and the MySQL exit code.
	output="$(clean_output "$output_dirty")"
	echo -e "$mysql_err $output"
}


function sql() {
	entry="$1"
	
	case "$action" in
		# Read Branch
		read)
		case "$style" in
			# Entry only, no timestamps. This is used for edit prep.
			clean)
			case "$entry_number" in
				all)
					echo "	SELECT entry
         					FROM entries;"
				''
				last)
					echo "	SELECT entry
                        			FROM entries
                        			WHERE entry_number = (
                                			SELECT MAX(entry_number)
                                			FROM entries
                               	 		);"
				''
				?)
					echo "	SELECT entry
                        			FROM entries
                        			WHERE entry_number IN ("$entry_number");"
				''
			''
			# Entry Number, Timestamp, and Entry. This is used most of the time.
			?)
			case "$entry_number" in
				all)
                               		echo "  SELECT *
                                        	FROM entries;"
				''
				last)
                                	echo "  SELECT *
                                        	FROM entries
                                      	 	WHERE entry_number = (
                                                	SELECT MAX(entry_number)
                                                	FROM entries
                                        	);"
				''
                      		?)
                               		echo "  SELECT *
                                        	FROM entries
                                        	WHERE entry_number IN ("$entry_number");"
				''
			''
		''
		# Write Branch
		write) 
			echo "	INSERT INTO entries (entry) VALUES (
                		CONCAT('"$entry"')
                		);"
		''
	
		# Edit Branch
		edit)
		case "$entry_number" in
			last)
				echo "	UPDATE entries
                        		SET entry = CONCAT('$entry')
                       	 		WHERE entry_number = (
                                		SELECT MAX(entry_number)
                                		FROM (SELECT * FROM entries) AS temp
                                	);"
			''
			?)
				echo "	UPDATE entries
                        		SET entry = CONCAT('$entry')
                        		WHERE (entry_number = "$entry_number");"
			''
		''
		# Delete Branch
		delete)
		case "$entry_number" in
			last)
				echo "	DELETE FROM entries
                        		WHERE entry_number = (                                                                                                          
						SELECT MAX(entry_number)                                                                                                
						FROM (SELECT * FROM entries) AS temp                                                                           
					);"
			''
			?)
			echo "	DELETE FROM entries
                        	WHERE entry_number IN ("$entry_number");"
			''
		''
}
