#!/bin/bash

function blog_delete() {

	if [ "$1" == "" ]; then
                echo -e "Which entries would you like to delete?:\n\tex) 7\n\tex) 1, 2, 5\n\tex) last"
                read DEL_NUMS
        else
                del_nums="$1"
        fi

	
	if [ "$del_nums" == "last" ]; then
		action="
                	DELETE FROM entries
                	WHERE entry_number = (
                                SELECT MAX(entry_number)
                                FROM entries
                                );

                	SELECT *
                	FROM entries;
        	"
	else
		action="
                        DELETE FROM entries
                        WHERE entry_number IN ("$del_nums");

                        SELECT *
                        FROM entries;
                "
	fi


	echo "Are you sure you want to permanently delete these entries?: (Y/N)"
	read del_ans


	if [ $del_ans == "Y" ] || [ $del_ans == "y" ]; then
		
		mysql -h "$MYSQL_HOST" -u "$MYSQL_USER" -p -D "$MYSQL_DATABASE" -e "$action" | grep -v '^[-]*$' > output_dirty

                if [ $? -eq 0 ]; then

                        sed -i 's/^\([0-9]\+\s[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\s[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\)/\n\n\n\1\n/g' output_dirty
                        sed -i 's/\\t/\t/g' output_dirty
                        sed -i 's/\\n/\n/g' output_dirty

                        cp output_dirty output
                        rm output_dirty

                        echo "Read all entries?: (Y/N)"
                        read read_ans

                        if [ "$read_ans" == "Y" ] || [ "$read_ans" == "y" ]; then
                                vim output
                                echo "Deletion completed."
				exit 0 
                        else
                                echo "Deletion completed."
                                exit 0
                        fi
                else
                        echo "Something went wrong. Nothing has been deleted."
                        exit 1
                fi
	else	
		echo "Nothing has been deleted."
		exit 1
	fi

}
