#!/bin/bash

function blog_edit() {

	if [ "$1" == "" ]; then
		echo -e "Which entry would you like to overwrite?:\n\tex) 7\n\tex)last"
		read edit_num
	else
		edit_num="$1"
	fi


	if [ "$2" == "" ]; then
                file_name="./entry"
        else
                file_name="$2"
        fi

        cp "$file_name" entry_dirty

	sed -i "s/'/', CHAR(39), '/g" entry_dirty
	sed -i "s/\"/', CHAR(34), '/g" entry_dirty
	sed -i "s/;/', CHAR(59), '/g" entry_dirty

	ENTRY_FILE=$(<entry_dirty)
	rm entry_dirty
	
	
	if [ "$edit_num" == "last" ]; then
                action="
                	UPDATE entries
               		SET entry = CONCAT('$ENTRY_FILE')
               		WHERE entry_number = (
                                SELECT MAX(entry_number)
                                FROM entries
                                );

                	SELECT *
                	FROM entries
                	WHERE entry_number = $edit_num;
                "
        else
		action="
			UPDATE entries
			SET entry = CONCAT('$ENTRY_FILE')
			WHERE (entry_number = $edit_num);
	
			SELECT *
                	FROM entries
                	WHERE entry_number = $edit_num;
	"
	fi
	

	echo "Are you sure you want to permanently overwrite this entry?: (Y/N)"
	read edit_ans


	if [ $edit_ans == "Y" ] || [ $edit_ans == "y" ]; then
		mysql -h "$MYSQL_HOST" -u "$MYSQL_USER" -p -D "$MYSQL_DATABASE" -e "$action" | grep -v '^[-]*$' > output_dirty
		
		if [ $? -eq 0 ]; then

        		sed -i 's/^\([0-9]\+\s[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\s[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\)/\n\n\n\1\n/g' output_dirty
        		sed -i 's/\\t/\t/g' output_dirty
        		sed -i 's/\\n/\n/g' output_dirty

        		cp output_dirty output
        		rm output_dirty

        		echo "Read last entry?: (Y/N)"
        		read read_ans

        		if [ "$read_ans" == "Y" ] || [ "$read_ans" == "y" ]; then
                		vim output
				echo "Overwrite completed."
				exit 0
        		else
				echo "Overwrite completed."
            	   		exit 0
			fi
		else
                	echo "Something went wrong. Nothing has been overwritten."
			exit 1
		fi
	else
		echo "Nothing has been overwritten."
              	exit 0
	fi

}
