#!/bin/bash

function main() {
	# Moves necessary files to a $PATH directory for ease of access.
        cp blog /usr/local/bin/blog
        cp blog_core /usr/local/bin/blog_core
	cp blog_sql /usr/local/bin/blog_sql
	cp startup /usr/local/bin/startup

	# Report results to user.
        if [ $? -eq 0 ]; then
                echo -e "Publish to /usr/local/bin successful.\nYou may now run commands using:\n\tblog ..."
                exit 0
        else
                echo "Something went wrong."
                exit 1
        fi
}

main
