#!/bin/bash

function main() {
	# Moves necessary files to a $PATH directory for ease of access.
        cp blog_module /usr/local/bin/blog_module
        cp blog /usr/local/bin/blog
	cp startup /usr/local/bin/startup

	# Report results to user.
        if [ $? -eq 0 ]; then
                echo -e "Publish to /usr/local/bin successful.\nYou may now run commands using:\n\tblog ..."
                exit 0
        else
                echo "Something went wrong."
                exit 1
        fi
}

main
