#!/bin/bash

function publish_tools() {	
	
	cp read /usr/local/bin/blog_read
	cp write /usr/local/bin/blog_write
	cp edit /usr/local/bin/blog_edit
	cp delete /usr/local/bin/blog_delete
	cp backup /usr/local/bin/blog_backup
	cp publish /usr/local/bin/blog_publish
	cp blog /usr/local/bin/blog
	
	if [ $? -eq 0 ]; then
		echo -e "Publish to /usr/local/bin successful.\nYou may now run commands using:\nblog ..."
		exit 0
	else
		echo "Something went wrong."
		exit 1
	fi
}
