#!/bin/bash

source blog_prompts

function blog_read() {
	
        if [ "$1" == "" ]; then
                echo -e "Which entries would you like to read?:\nex) 7\nex) 1, 2, 5\nex) last\nex)all"
                read READ_NUMS
        else
                READ_NUMS="$1"
        fi

	
	if [ "$READ_NUMS" == "all" ]; then
		SQL="
			SELECT *
			FROM entries;
		"
	elif [ "$READ_NUMS" == "last" ]; then
		SQL="
                      	SELECT *
                       	FROM entries
                      	WHERE entry_number = (
                        	SELECT MAX(entry_number)
                             	FROM entries
                               	);
             	"
	else
		SQL="
                    	SELECT *
                       	FROM entries
                  	WHERE entry_number IN ("$READ_NUMS");
          	"
		
	fi

	mysql -h "$MYSQL_HOST" -u "$MYSQL_USER" -p -D "$MYSQL_DATABASE" -e "$SQL" | grep -v '^[-]*$' > output_dirty

	if [ $? -eq 0 ]; then
		sed -i 's/^\([0-9]\+\s[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\s[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\)/\n\n\n\1\n/g' output_dirty
		sed -i 's/\\t/\t/g' output_dirty
		sed -i 's/\\n/\n/g' output_dirty

		cp output_dirty output
		rm output_dirty

		vim -c ":set wrap linebreak" output
		
		echo "Read successful."
		exit 0
	else
		echo "Something went wrong."
		exit 1
	fi
}
