#!/bin/bash

function blog_read() {
	
        if [ "$1" == "" ]; then
                echo -e "Which entries would you like to read?:\n\tex) 7\n\tex) 1, 2, 5\n\tex) last\n\tex)all"
                read read_nums
        else
                read_nums="$1"
        fi

	
	if [ "$read_nums" == "all" ]; then
		action="
			SELECT *
			FROM entries;
		"
	elif [ "$read_nums" == "last" ]; then
		action="
                      	SELECT *
                       	FROM entries
                      	WHERE entry_number = (
                        	SELECT MAX(entry_number)
                             	FROM entries
                               	);
             	"
	else
		action="
                    	SELECT *
                       	FROM entries
                  	WHERE entry_number IN ("$read_nums");
          	"
		
	fi

	mysql -h "$MYSQL_HOST" -u "$MYSQL_USER" -p -D "$MYSQL_DATABASE" -e "$action" | grep -v '^[-]*$' > output_dirty

	if [ $? -eq 0 ]; then
		sed -i 's/^\([0-9]\+\s[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\s[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\)/\n\n\n\1\n/g' output_dirty
		sed -i 's/\\t/\t/g' output_dirty
		sed -i 's/\\n/\n/g' output_dirty

		cp output_dirty output
		rm output_dirty

		vim -c ":set wrap linebreak" output
		
		echo "Read successful."
		exit 0
	else
		echo "Something went wrong."
		exit 1
	fi
}
