#!/bin/bash

function blog_write() {

	if [ "$1" == "" ]; then
		file_name="./entry"
	else
		file_name="$1"
	fi

	cp "$file_name" entry_dirty

	sed -i "s/'/', CHAR(39), '/g" entry_dirty
	sed -i "s/\"/', CHAR(34), '/g" entry_dirty
	sed -i "s/;/', CHAR(59), '/g" entry_dirty

	ENTRY_FILE=$(<entry_dirty)
	rm entry_dirty

	action="
		INSERT INTO entries (entry) VALUES (
		CONCAT('"$ENTRY_FILE"')
		);

		SELECT *
                FROM entries
                WHERE entry_number = (
                	SELECT MAX(entry_number)
                	FROM entries
                	);
	"

	mysql -h "$MYSQL_HOST" -u "$MYSQL_USER" -p -D "$MYSQL_DATABASE" -e "$action" | grep -v '^[-]*$' > output_dirty
	
	if [ $? -eq 0 ]; then

        	sed -i 's/^\([0-9]\+\s[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\s[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\)/\n\n\n\1\n/g' output_dirty
	        sed -i 's/\\t/\t/g' output_dirty
        	sed -i 's/\\n/\n/g' output_dirty

 		cp output_dirty output
       	 	rm output_dirty
		
		echo "Write successful."
		
		echo "Read last entry?: (Y/N)"
		read read_ans

		if [ "$read_ans" == "Y" ] || [ "$read_ans" == "y" ]; then
			vim output
			exit 0
		elif [ "$read_ans" == "N" ] || [ "$read_ans" == "n" ]; then
			exit 0
		fi
	else
		echo "Something went wrong."
		exit 1
	fi

}
